tap "homebrew/bundle"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Bash scripts that integrate bat with various command-line tools
brew "bat-extras"
# Modern, maintained replacement for ls
brew "eza"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
vscode "bradlc.vscode-tailwindcss"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "dsznajder.es7-react-js-snippets"
vscode "ecmel.vscode-html-css"
vscode "esbenp.prettier-vscode"
vscode "grapecity.gc-excelviewer"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "prisma.prisma"
vscode "qwtel.sqlite-viewer"
vscode "ritwickdey.liveserver"
vscode "silvenon.mdx"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "unifiedjs.vscode-mdx"
vscode "vscode-icons-team.vscode-icons"
vscode "xyc.vscode-mdx-preview"
vscode "yzhang.markdown-all-in-one"
